language: node_js
node_js:
   - "6.9.4"
   - "7.4.0"
cache: yarn
matrix:
  allow_failures:
    - node_js: "7.4.0"
  fast_finish: true
notifications:
  webhooks: https://ambrosio-tele.herokuapp.com/ambrosio_bot/travisci/133188453
  on_start: true
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libicu-dev
