language: node_js
dist: trusty
node_js:
   - "8.11.1"
cache:
  directories:
    - node_modules
matrix:
  allow_failures:
    - node_js: "4.4.0"
  fast_finish: true
notifications:
  email: false
  webhooks: https://ambrosio-tele.herokuapp.com/ambrosio/travisci/%23general
  on_success: always # default: always
  on_failure: always # default: always
  on_start: always   # default: never
env:
  - CXX=g++-5 CC=gcc-5
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - libicu-dev
  postgresql: "9.4"
services:
  - postgresql
before_script:
  - psql -c 'create database storage;' -U postgres
  - psql -c "CREATE TABLE hubot ( id CHARACTER VARYING(1024) NOT NULL, storage JSON, CONSTRAINT hubot_pkey PRIMARY KEY (id)); INSERT INTO hubot VALUES(1, NULL);" -U postgres storage
before_install:
  - npm install -g npm@'=5.8.0'
  - npm --version
